name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests and Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the version of Python to use

      # Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest to test the Python project
      - name: Run pytest
        run: |
          pytest

      # Set up Node.js for Prettier
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js

      # Install Prettier
      - name: Install Prettier
        run: npm install -g prettier

      # Run Prettier to check code formatting
      - name: Run Prettier for code formatting
        run: |
          prettier --check "templates/*.html"

